from .Utils import startsWith
from .Utils import endsWith

SPELL_FAILED_TYPE = [
    "A Frost Wyrm is already active.",
    "A Stampede is already active.",
    "A more powerful spell is already active",
    "A mysterious force prevents you from opening the chest.",
    "A summon is already pending",
    "A trap is already placed there.",
    "Alex broke your quest! Thank him later!",
    "All party members must be present to do that.",
    "Already at Resource cap",
    "Already at Valor cap",
    "Already commended by this faction",
    "Already open",
    "Ambassador Slaghammer is already your prisoner.",
    "Ammo needs to be in the paper doll ammo slot before it can be fired.",
    "An aura is currently disabling this spell",
    "Another action is in progress",
    "Both Frost Fever and Blood Plague must be present on the target.",
    "Bouldercrag's War Horn can only be used within 10 yards of Valduran the Stormborn.",
    "Can only be placed near Shatterhorn",
    "Can only be used in the evening.",
    "Can only be used on AFK players.",
    "Can only be used on Hati.",
    "Can only be used on Inert Tide Watchers or Inert Voodoo Masks.",
    "Can only use in battlegrounds",
    "Can only use indoors",
    "Can only use outside",
    "Can only use while mounted",
    "Can only use while swimming",
    "Can't Add Companion To Your Account",
    "Can't cast as ghost",
    "Can't cast that right now.",
    "Can't cast while fatigued",
    "Can't cast while trading",
    "Can't create any more Work Orders of that type.",
    "Can't do that while charmed",
    "Can't do that while confused",
    "Can't do that while falling",
    "Can't do that while fleeing",
    "Can't do that while in Ghost Wolf form.",
    "Can't do that while in demon form (yet)",
    "Can't do that while moving",
    "Can't do that while silenced",
    "Can't do that while stunned",
    "Can't take while being damaged!",
    "Can't target player controlled units",
    "Can't target players",
    "Can't target trivial",
    "Can't use items while shapeshifted",
    "Can't use that ability while pacified",
    "Can't use while Idle",
    "Can't use while Inactive",
    "Cannot be cast on shapeshifted target.",
    "Cannot resurrect someone who has surrendered to madness",
    "Cannot use during a boss encounter.",
    "Cannot use on the ground",
    "Cannot use while swimming",
    "Chimaeron is too calm to tame right now.",
    "Creature is not skinnable",
    "Creature must be looted first",
    "Does not work on critters.",
    "Dueling isn't allowed here.",
    "Failed attempt",
    "Failed to Upgrade Pet",
    "First, Overload the Defective Generator, Activate the Leaky Stove, and Drop a Cigar on the Flammable Bed.",
    "Fizzled",
    "Floating mounts are not allowed here",
    "Flying mounts are not allowed here",
    "Follower must be max level.",
    "Food cannot eat food",
    "Free the Drake from the net first!",
    "Frostmourne has rendered you unable to resurrect.",
    "Ground mounts are not allowed here",
    "Immune",
    "Internal error",
    "Interrupted",
    "Invalid target",
    "Item already has the maximum number of charges.",
    "Item already has this enchant visual.",
    "Item cannot be disenchanted",
    "Item cannot be enchanted in trade",
    "Item cannot be obliterated",
    "Item is already enchanted",
    "Item is gone",
    "Item is not Azerite empowered",
    "Item is not a weapon.",
    "Item is not ready yet",
    "Item must be soulbound.",
    "Item's enchant visual cannot be modified.",
    "Leave Instance Group to exit.",
    "Missing Reagents: Dark Matter",
    "Must be closer to one of Gazlowe's objectives to deploy!",
    "Must be closer to one of Thaelin's objectives to deploy!",
    "Must be in Bear Form",
    "Must be in Cat Form",
    "Must be standing near the injured Chromie in Mount Hyjal.",
    "Must be used near an oil slick.",
    "Must have a Melee Weapon equipped in both hands",
    "Must have the proper item equipped",
    "Must know previous spell rank to learn.",
    "Needs repairs.",
    "No charges remain",
    "No enemies near target.",
    "No fishing nodes nearby.",
    "No fully depleted runes.",
    "No lootable corpse in range",
    "No magic to consume",
    "No more charges.",
    "No path available",
    "No pockets to pick",
    "No power choices to undo.",
    "No skinnable corpse in range",
    "No target",
    "No targets close enough to bluff.",
    "No valid flask present.",
    "Not available for Starter accounts",
    "Not enough Ammunition!",
    "Not enough Ancient Mana.",
    "Not enough Runic Power",
    "Not enough Work Orders pending for that building.",
    "Not enough endurance",
    "Not enough fuel",
    "Not enough health",
    "Not enough health!",
    "Not in World PvP zone.",
    "Not yet recovered",
    "Nothing left to discover.",
    "Nothing to dispel",
    "Nothing to steal",
    "Only Death Knights may enter Ebon Hold.",
    "Only GMs may use that. Your account has been reported for investigation.",
    "Only one elemental spirit on a target at a time.",
    "Only other members of their Hivemind may join with them.",
    "Out of ammo",
    "Out of coins! Pickpocket humanoids to get more.",
    "Out of range",
    "Paragon Reputation is not available until a higher level.",
    "Requires 1 Withered Berserker",
    "Requires 100 Imp Meat.",
    "Requires 2 Withered Berserkers",
    "Requires 2 Withered Mana-Ragers",
    "Requires 20 Ammunition!",
    "Requires 30 Ammunition!",
    "Requires 600 Mining or Blacksmithing",
    "Requires Battle Rations or Meaty Haunch",
    "Requires Battle for Azeroth Pathfinder skill.",
    "Requires Bear Form.",
    "Requires Bone Shield charges",
    "Requires Brittle Root",
    "Requires Broken Isles Pathfinder skill.",
    "Requires Cat Form.",
    "Requires Cloud Serpent Riding skill",
    "Requires Corpse Dust",
    "Requires Corpse Dust if the target is not dead and humanoid.",
    "Requires Draenor Pathfinder skill.",
    "Requires Engineering (350)",
    "Requires Gnomish Engineering",
    "Requires Goblin Engineering",
    "Requires Inferno Shot Ammo!",
    "Requires Krasari Iron",
    "Requires Laborer's Tool",
    "Requires Liquid Fire, Jungle Hops, or Spirit-kissed Water",
    "Requires Mage Tower",
    "Requires Misplaced Keg",
    "Requires Morrison's Master Key.",
    "Requires Northrend Engineering (25)",
    "Requires Opposable Thumbs.",
    "Requires Pa'ku to be your chosen loa.",
    "Requires Remote Control Fireworks. Return to Hobart Grapplehammer to get more.",
    "Requires Single-Stage Booster Rockets. Return to Hobart Grapplehammer to get more.",
    "Requires Snake Oil",
    "Requires Spirit Lodge",
    "Requires Spirit-Kissed Water",
    "Requires The Thunder Forge.",
    "Requires Unexploded Cannonball",
    "Requires V.I.G.O.R. Engaged.",
    "Requires Wisdom of the Four Winds skill",
    "Requires a Brimming Keystone.",
    "Requires a Felforged Cudgel!",
    "Requires a Leyspine Missile",
    "Requires a Nether Portal Disruptor.",
    "Requires a Song Scroll to function.",
    "Requires a faster time with the basic racer",
    "Requires a level 3 Mage Tower.",
    "Requires a level 3 Spirit Lodge.",
    "Requires a location that is attuned with the Naz'jar Battlemaiden.",
    "Requires a nearby Soul Fragment.",
    "Requires a nearby target.",
    "Requires an active Healing Rain.",
    "Requires an artifact weapon.",
    "Requires apprentice riding skill",
    "Requires artisan riding skill",
    "Requires at least 10 living withered",
    "Requires at least 14 living withered",
    "Requires at least 18 living withered",
    "Requires both currents connected.",
    "Requires cold weather flying skill",
    "Requires either a Conjured Mana Pudding or Conjured Mana Fritter.",
    "Requires expert riding skill",
    "Requires flight master's license skill",
    "Requires journeyman riding skill",
    "Requires level 65",
    "Requires master riding skill",
    "Requires that you be wearing the Warsong Orc Disguise.",
    "Requires the Darkmoon Faire to be open.",
    "Requires the magmawyrm resurrection chamber in the back of the Maw of Neltharion.",
    "Requires water surface",
    "Requires you to be near a Mantid Feeder in the Heart of Fear.",
    "Skill not high enough",
    "Skill too high.",
    "Something bad happened, and we want to display a custom message!",
    "Spell Failed to create area trigger",
    "Spell cannot be cast on a damage immune target.",
    "Spell cannot be cast on a mounted unit.",
    "Spell cannot be cast on stealthed target.",
    "Spell not learned",
    "Statue is out of range of the target.",
    "Target can't be charmed",
    "Target cannot already have a Orb of Power.",
    "Target cannot be resurrected",
    "Target cannot benefit from that spell",
    "Target has a resurrection pending",
    "Target has no ranged weapons equipped",
    "Target has no weapons equipped",
    "Target is alive",
    "Target is already affected by Stardust No. 2.",
    "Target is already affected by a similar effect",
    "Target is currently dueling",
    "Target is currently in free-for-all PvP combat",
    "Target is friendly",
    "Target is hostile",
    "Target is in combat",
    "Target is locked to another raid instance",
    "Target is not a ghost",
    "Target is not a player",
    "Target is not in a sanctuary",
    "Target is not in your party",
    "Target is not in your party or raid group",
    "Target is not on the ground",
    "Target is tapped",
    "Target is too enraged to be charmed",
    "Target is too far away.",
    "Target is too high level",
    "Target is too low level",
    "Target must be dead.",
    "Target must be directly in front of you.",
    "Target must be in this instance",
    "Target must be undead.",
    "Target needs to be behind you.",
    "Target needs to be in front of you.",
    "Target not in line of sight",
    "Target too close",
    "Target's health is too low",
    "That ability is not available to your pet",
    "That ability requires combo points",
    "That anti-venom is not strong enough to dispel that poison",
    "That building is not in your garrison.",
    "That can only be used on a Ice Heart Jormungar Spawn.",
    "That creature is already being tamed",
    "That demon's health is already full.",
    "That follower already has a temporary ability.",
    "That follower already has that ability.",
    "That follower has no available ability slots.",
    "That follower is already max level.",
    "That follower is currently assigned to a building.",
    "That follower is currently on a mission.",
    "That follower's power level exceeds the power of this spell.",
    "That follower's power level is too low for the power of this spell.",
    "That follower's quality exceeds the power of this spell.",
    "That food's level is not high enough for your pet",
    "That glyph cannot be inscribed there.",
    "That glyph is already inscribed in your spellbook.",
    "That glyph requires a specialization.",
    "That is already being used",
    "That item cannot be modified.",
    "That item cannot be obliterated.",
    "That item is not a valid target.",
    "That mission is already complete.",
    "That mission is not in progress.",
    "That player has a pending Totemic Revival.",
    "That specialization has been disabled",
    "The Arkonite Protector is not in range.",
    "The Goblin All-In-1-Der Belt's battery is depleted.",
    "The Imbued Scourge Shroud will only work when equipped in the Temple City of En'kilah.",
    "The Nightmare obscures your vision.",
    "The Sentinax cannot open another portal right now.",
    "The Sentinax is not patrolling this area.",
    "The ballista cannot be used while on fire.",
    "The building is not ready to be activated.",
    "The door is locked.",
    "The portal is not yet open.  Continue helping the druids at the Sanctuary of Malorne.",
    "The potions have all been depleted by Professor Putricide.",
    "The spell cannot be cast on beastmaster or invis god targets.",
    "The spell is not available to you",
    "The target can't be in a pet battle",
    "The target can't be in combat",
    "The target has no Festering Wounds.",
    "The target must be bound to you.",
    "The targeted garrison follower must be at least of Epic quality to do that.",
    "The weather isn't right for that",
    "There are no Wild Imps to sacrifice.",
    "There are no explosives available.",
    "There are no gems in this",
    "There are no nearby corpses to eat",
    "There are no nearby corpses to use.",
    "There are no unlocked flight points nearby to take you to.",
    "There are no valid corpses nearby.",
    "There are no valid targets within range.",
    "There are too many Mutated Abominations.",
    "There aren't any fish here",
    "There is no available seat",
    "There is nobody to eject!",
    "There is nothing interesting posted here right now.",
    "There is nothing to be fetched.",
    "There isn't enough acid left to store this transformation.",
    "There's nothing further you can learn.",
    "This Apexis Sentinel requires energy from a nearby Apexis Pylon to be powered up.",
    "This goblin is all partied out!",
    "This item requires Primal Obliterum to upgrade.",
    "This item requires a Flight Master's Whistle.",
    "This item requires basic Obliterum to upgrade.",
    "This item's level is too high for this upgrade.",
    "This partygoer needs a bucket!",
    "This partygoer wants some more bubbly.",
    "This partygoer wants some more hors d'oeuvres.",
    "This partygoer wants to dance with you.",
    "This partygoer wants to see some fireworks.",
    "This spell is already known",
    "This spell may only be used on Helpless Wintergarde Villagers that have not been rescued.",
    "This spell requires active mushrooms for you to detonate.",
    "This teleport crystal cannot be used until the teleport crystal in Dalaran has been used at least once.",
    "Three fawns are already following you!",
    "To use this mount in the current area you must be above water.",
    "To use this mount in the current area you must be underwater.",
    "To use this mount in the current area you must not be at the water's surface.",
    "Toy Use Limit Reached",
    "Toy is already in your collection",
    "Tried to enchant a trade item, but not trading",
    "Tried to enchant an item that didn't exist",
    "Ulthalesh has no power without souls.",
    "Underwater mounts are not allowed here",
    "Unknown phenomenon is preventing a connection to the Leyline.",
    "Unknown reason",
    "Uuna is missing.",
    "Wait until the Onyx Serpent is directly overhead.",
    "Water too shallow",
    "What are you doing? Only aim that thing at Wilhelm!",
    "Will only open to one wielding the power that echoes that of the Augari.",
    "Wrong Faction",
    "Wrong Pet Type",
    "You already control a charmed creature",
    "You already control a summoned creature",
    "You already have a Hot Rod.",
    "You already have a Mallet of Thunderous Skins.",
    "You already have a Mana Gem in your bank.",
    "You already have a River Boat.",
    "You already have a Silas' Sphere of Transmuation.",
    "You already have a piece of Murloc Slop.",
    "You already have an Iwen's Enchanting Rod.",
    "You already have enough Forsaken Troopers.",
    "You already have maximum rage",
    "You already have that follower.",
    "You already have that mission.",
    "You already have the max number of recruits.",
    "You already have the max number of volunteers.",
    "You already have the maximum amount of Outcasts following you.",
    "You already have the maximum amount of honor.",
    "You already have the maximum number of ships your shipyard can support.",
    "You already have three Dragonmaw allies following you.",
    "You already know that blueprint.",
    "You already own a garrison.",
    "You already possess all of the knowledge contained in these pages.",
    "You are already Well Fed.",
    "You are already a member of the Brawler's Guild.",
    "You are already carrying a captured Argent Crusader. You must return to the Argent Vanguard infirmary and drop off your passenger before you may pick up another.",
    "You are already disguised!",
    "You are already holding something in your hand. You must throw the creature in your hand before picking up another.",
    "You are already on that quest.",
    "You are blocked by a structure above you.",
    "You are bound to Draenor by Archimonde's magic.",
    "You are busy looting",
    "You are carrying the maximum amount of Blackrock Munitions.",
    "You are carrying too much Iron",
    "You are dead",
    "You are facing the wrong way.",
    "You are flying.",
    "You are higher than the max usable level for this spell.",
    "You are in combat",
    "You are in flight",
    "You are in shapeshift form",
    "You are in the wrong class specialization.",
    "You are in the wrong zone.",
    "You are missing pieces of the Armory Key or do not have enough Dendrite Clusters.",
    "You are mounted.",
    "You are not Electrified.",
    "You are not carrying a passenger. There is nobody to drop off.",
    "You are not eligible for any new missions.",
    "You are not high enough level",
    "You are not in control of your actions",
    "You are not the correct Rank to use this item.",
    "You are not the correct class for that mount.",
    "You are not the correct specialization.",
    "You are not wearing a shirt!",
    "You are on a transport",
    "You are possessed",
    "You are the Party Leader.",
    "You are too close to enemies",
    "You are too far from the bouy.",
    "You are too wise and powerful to gain any benefit from that item.",
    "You are unable to have both Beacon of Light and Beacon of Faith on the same target.",
    "You are unable to move",
    "You are within 10 yards of another Argent Lightwell.",
    "You are within 10 yards of another Makeshift Dynamite.",
    "You aren't in a Party.",
    "You can already rename your pet",
    "You can no longer resurrect during combat",
    "You can not change specializations while in Combat Training.",
    "You can not do this. You have more than 3 hours of online time. ",
    "You can not do this. You have more than 5 hours of online time",
    "You can only benefit from the Ritual of Doom once per day.",
    "You can only do that in an arena.",
    "You can only have one Healing Rain active at a time.",
    "You can only have one treasure map mission at a time.",
    "You can only have one waygate open. Disable an activated waygate first.",
    "You can only have three waygates open. Disable an activated waygate first.",
    "You can only have two waygates open. Disable an activated waygate first.",
    "You can only push Sad Panda towards Sad Panda Town!",
    "You can only use this on an object you own",
    "You can't cast that here",
    "You can't do that in a battleground.",
    "You can't do that in a raid instance.",
    "You can't do that in a rated battleground.",
    "You can't do that in an LFG Dungeon.",
    "You can't do that in an arena.",
    "You can't do that right now.",
    "You can't do that to targets holding the flag.",
    "You can't do that while Cycloned",
    "You can't do that while a Mythic Keystone is active.",
    "You can't do that while a Scenario is in progress.",
    "You can't do that while holding Empowered Ore.",
    "You can't do that while holding an Orb of Power.",
    "You can't do that while holding the flag.",
    "You can't do that while in the barber shop",
    "You can't do that while jumping or falling.",
    "You can't do that while rooted.",
    "You can't do that while shapeshifted.",
    "You can't do that while you are a mercenary",
    "You can't do that while you are immune",
    "You can't do that yet",
    "You can't mount here.",
    "You can't mount while affected by that shapeshift.",
    "You can't risk getting the grummels wet!",
    "You can't start a duel while invisible",
    "You can't start a duel while stealthed",
    "You can't take actions right now.",
    "You can't use that here.",
    "You can't use that item",
    "You can't use that mount.",
    "You can't use the new item",
    "You cannot Release Spirit yet.",
    "You cannot build any more siege vehicles.",
    "You cannot cast that while talented into Voodoo Totem.",
    "You cannot change specializations right now.",
    "You cannot charm any more withered.",
    "You cannot deconstruct Elementium Gem Clusters while collecting them!",
    "You cannot do that right now.",
    "You cannot do that while on a Class Trial.",
    "You cannot do that while under Suppressive Fire.",
    "You cannot gain additional reputation with this item.",
    "You cannot inscribe a glyph there yet.",
    "You cannot jump to another boulder yet.",
    "You cannot mill that",
    "You cannot perform the Ritual of Doom while attempting to summon the sisters.",
    "You cannot reach the latch.",
    "You cannot read the soldier's dog tag without your headlamp on.",
    "You cannot recruit any more of that troop type.",
    "You cannot shapeshift while riding Stormtalon",
    "You cannot steal that while guards are on duty.",
    "You cannot summon another gargoyle yet.",
    "You cannot supervise more than 5 Arrested Cultists at a time.",
    "You cannot target an elemental or mechanical corpse.",
    "You cannot target friendly units outside your party.",
    "You cannot transform right now",
    "You cannot use Call Pet while Lone Wolf is active.",
    "You cannot use that in a PvP instance.",
    "You cannot use the dice again yet.",
    "You cannot use the gateway yet.",
    "You do not have Deadly Poison or Wound Poison active.",
    "You do not have a pet.",
    "You do not have enough currency to cast this spell.",
    "You do not have enough withered to do that.",
    "You do not have the Mallet of Thunderous Skins.",
    "You do not know how to tame Blood Beasts.",
    "You do not know how to tame Direhorns.",
    "You do not know how to tame Feathermanes.",
    "You do not know how to tame or obtain lore about Mechs.",
    "You do not like Fel Eggs and Ham.",
    "You do not meet the level requirements for this item.",
    "You don't have a statue summoned.",
    "You don't have any Artifact Fragments.",
    "You don't have anything to throw! Find a Vargul and use Gymer Grab to pick one up!",
    "You don't have enough Nethershards.",
    "You don't have enough currency to do that.",
    "You don't have enough health.",
    "You don't know that skill.",
    "You don't own a garrison.",
    "You have already captured enough wild cluckers.",
    "You have already defeated enough of them.",
    "You have already destroyed the KTC Oil Platform.",
    "You have already entered in to this trade agreement.",
    "You have already launched enough cages.",
    "You have already learned the spell",
    "You have already read that treasure map.",
    "You have already rescued 6 Survivors.",
    "You have already sampled sap from this Feeder.",
    "You have already used a Vantus Rune this week.",
    "You have bound enough Highborne souls. Return to Arcanist Valdurian.",
    "You have collected this mount but it is not usable on this character.",
    "You have insufficient Blood Charges.",
    "You have learned all that you can about your artifact.",
    "You have learned everything from that book",
    "You have no Fire Mines deployed.",
    "You have no Iron to collect",
    "You have no Wood to collect.",
    "You have no active enchantment to unleash.",
    "You have no active glyphs to remove.",
    "You have no available Wild Imps.",
    "You have no pending Work Orders for that building.",
    "You have no spirit active.",
    "You have no target or your target is too far away.",
    "You have no target.",
    "You have not obtained any background filters.",
    "You have not provided enough items to cast this spell",
    "You have not unlocked the Flight Whistle for this zone.",
    "You have provided too many items to cast this spell",
    "You have run out of Blackrock Munitions.",
    "You have too many of that item already",
    "You haven't selected a champion",
    "You may not bite other vampires.",
    "You may not change specialization while a trial is in progress.",
    "You may not change talent specializations during a celestial challenge.",
    "You may only call down a Wintergarde Gryphon in Wintergarde Keep or the Carrion Fields.",
    "You may only call down a stampede on Harold Lane.",
    "You may only call for the aid of a Wyrmrest Vanquisher in Wyrmrest Temple, The Dragon Wastes, Galakrond's Rest or The Wicked Coil.",
    "You may only carry one type of Blackrock Munitions.",
    "You may only use the Pouch of Crushed Bloodspore on Gammothra or other magnataur in the Bloodspore Plains and Gammoth.",
    "You may only use this item while your garrison is under attack.",
    "You must be a Mercenary to use this trinket.",
    "You must be a party leader to queue your group.",
    "You must be above the Enslaved Pearl Miner.",
    "You must be affected by the Spirit Powder to take the phylactery.",
    "You must be at a Shrine to make an offering to a Loa.",
    "You must be at least 40 yards away from all other Oil Drilling Rigs.",
    "You must be at your shipyard.",
    "You must be behind your target.",
    "You must be close to a marked tree.",
    "You must be closer to a plague wagon in order to drop off your 7th Legion Siege Engineer.",
    "You must be closer to a sinkhole to use your map.",
    "You must be closer to the buoy!",
    "You must be flagged for PvP.",
    "You must be in Cat Form.",
    "You must be in an inn to strum that guitar.",
    "You must be in combat.",
    "You must be in front of your target.",
    "You must be in stealth mode.",
    "You must be near the Bloodied Court gate.",
    "You must be near the Maiden of Winter's Breath Lake.",
    "You must be near the sunken ship at Sapphire's End in the Jade Forest.",
    "You must be standing to do that",
    "You must be transformed by Polyformic Acid.",
    "You must be unsheathed",
    "You must be wielding the Underlight Angler.",
    "You must be within range of a Helpless Wintergarde Villager.",
    "You must choose a specialization to use Ascendance.",
    "You must dismiss your current pet first.",
    "You must first select a Proto-Drake Egg.",
    "You must have 3 or fewer players.",
    "You must have a Felguard.",
    "You must have a Magma, Flametongue, or Fire Elemental Totem active.",
    "You must have a demonic circle active.",
    "You must have a lance equipped.",
    "You must have an artifact weapon equipped.",
    "You must have an open stable slot.",
    "You must have at least one Flame Shock active.",
    "You must obtain a Flight Master's License before using this spell.",
    "You must reach Artifact Knowledge level 25 to use the Tome.",
    "You must reach level 58 to use this portal.",
    "You must reach level 85 to use this portal.",
    "You must select a specialization first.",
    "You must target a Dread Gladiator's item to upgrade.",
    "You must target a Fjord Hawk.",
    "You must target a Fjord Turkey.",
    "You must target a Sinister Gladiator's item to upgrade.",
    "You must target a weakened chill nymph.",
    "You must target the corpse of a Seabrush Terrapin, Scourgut Remora, or Spinescale Hammerhead.",
    "You must wait for customers to get in line before you can select them to be seated.",
    "You need Beatface the Sparring Arena gladiator to break this!",
    "You need Evasive Charges",
    "You need to be closer to Aggra's Air Totem, in the west.",
    "You need to be closer to Aggra's Earth Totem, in the east.",
    "You need to be closer to Aggra's Fire Totem, near Thrall.",
    "You need to be closer to Aggra's Water Totem, in the north.",
    "You need to be facing the ships from the rescue balloon.",
    "You need to be in a Shredder to chop this up!",
    "You need to choose a character specialization",
    "You need to select a customer who is waiting in line first.",
    "You should remove the cannon's Electrokinetic Defense Grid first.",
    "You should remove the cannon's Heavy Iron Plating first.",
    "You're already carrying repair parts.",
    "You're carrying too much Wood.",
    "You're too far away from Zafod's Transponster! The rocket pack won't fire.",
    "You've already collected these appearances",
    "You've already collected this appearance.",
    "You've already sent in the Gasbot and destroyed headquarters!",
    "You've created enough ghouls. Return to Gothik the Harvester at Death's Breach.",
    "You've reached the maximum number of Artifact Research Notes available.",
    "Your Artifact is at full power.",
    "Your Artifact is too powerful to be modified by that item",
    "Your Enchanting skill is not high enough to disenchant that",
    "Your Iron Rune Construct is out of range.",
    "Your Pet is out of range of the target.",
    "Your attendant already has an Argent Pony",
    "Your cast didn't land in fishable water",
    "Your companion does not want to come here.  Go further from the Sundered Shard.",
    "Your objective is already complete.",
    "Your pack of volen is already full!",
    "Your pet doesn't like that food.",
    "Your pet is already at your level.",
    "Your pet is dead.",
    "Your pet is not high enough level",
    "Your pet must be attacking a target.",
    "Your reputation isn't high enough",
    "Your skill is too high for this item.",
    "Your soul belongs to the Lich King",
    "Your supplies are frozen.",
    "Your talent specialization does not match the selected challenge.",
    "Your target is already embiggified.",
    "Your target is dead",
    "Your target is in flight",
    "Your target must be Shackled.",
    "Your target must be below 35% health.",
    "Your total pet maximum is already this high.",
    "Your vision of the target is obscured",
    "Your weapon hand is empty",
    "Your weapon has overheated.",
    "Yu'lon is already active."
]

SPELL_FAILED_TYPE_WARG = [
    "Can't do that while {0:s}",
    "Missing reagent: {0:s}",
    "Must be in {0:s}",
    "Must have a {0:s} equipped",
    "Must have a {0:s} equipped in the main hand",
    "Must have a {0:s} equipped in the offhand",
    "Requires Fishing {0:d}",
    "Requires engaging {0:s}",
    "Requires exotic ammo: {0:s}",
    "Requires {0:d} {1:s}.",
    "Requires {0:s}",
    "Requires: {0:s}",
    "That glyph is invalid for your {0:s} specialization.",
    "You can only cast {0:s} {1:d} times a week.",
    "You can't change that talent choice while {0:s} is on cooldown.",
    "You may only have one glyph of the {0:s} type.",
    "You need to be in {0:s}.",
    "Your skill is not high enough.  Requires {0:s} ({1:d})."
]


def parseSpellFailed(msg):
    try:
        index = SPELL_FAILED_TYPE.index(msg)
        if index != -1:
            return index, list()
    except ValueError:
        pass

    values = list()
    if startsWith(msg, "Can't do that while "):
        # "Can't do that while {0:s}"
        index = len(SPELL_FAILED_TYPE) + 0
        values.append(msg[20:])
    
    elif startsWith(msg, "Missing reagent: "):
        # "Missing reagent: {0:s}"
        index = len(SPELL_FAILED_TYPE) + 1
        values.append(msg[17:])
    
    elif startsWith(msg, "Must be in "):
        # "Must be in {0:s}"
        index = len(SPELL_FAILED_TYPE) + 2
        values.append(msg[11:])
    
    elif startsWith(msg, "Must have a "):
        if endsWith(msg, " equipped"):
            # "Must have a {0:s} equipped"
            index = len(SPELL_FAILED_TYPE) + 3
            values.append(msg[12:-9])
        elif endsWith(msg, " equipped in the main hand"):
            # "Must have a {0:s} equipped in the main hand"
            index = len(SPELL_FAILED_TYPE) + 4
            values.append(msg[12:-26])
        elif endsWith(msg, " equipped in the offhand"):
            # "Must have a {0:s} equipped in the offhand"
            index = len(SPELL_FAILED_TYPE) + 5
            values.append(msg[12:-24])
        else:
            print(msg)
            assert(False)
    
    elif startsWith(msg, "Requires Fishing "):
        # "Requires Fishing {0:d}"
        index = len(SPELL_FAILED_TYPE) + 6
        values.append(int(msg[17:]))
    
    elif startsWith(msg, "Requires engaging "):
        # "Requires engaging {0:s}"
        index = len(SPELL_FAILED_TYPE) + 7
        values.append(msg[18:])
    
    elif startsWith(msg, "Requires exotic ammo: "):
        # "Requires exotic ammo: {0:s}"
        index = len(SPELL_FAILED_TYPE) + 8
        values.append(msg[22:])
    
    elif startsWith(msg, "Requires ") and endsWith(msg, "."):
        # "Requires {0:d} {1:s}."
        index = len(SPELL_FAILED_TYPE) + 9
        space = msg.index(" ", 9)
        values.append(int(msg[9 : space]))
        values.append(msg[space + 1 : -1])
    
    elif startsWith(msg, "Requires "):
        # "Requires {0:s}"
        index = len(SPELL_FAILED_TYPE) + 10
        values.append(msg[9:])
    
    elif startsWith(msg, "Requires: "):
        # "Requires: {0:s}"
        index = len(SPELL_FAILED_TYPE) + 11
        values.append(msg[10:])
    
    elif startsWith(msg, "That glyph is invalid for your ") and endsWith(msg, " specialization."):
        # "That glyph is invalid for your {0:s} specialization."
        index = len(SPELL_FAILED_TYPE) + 12
        values.append(msg[31:-16])
    
    elif startsWith(msg, "You can only cast ") and endsWith(msg, " times a week."):
        # "You can only cast {0:s} {1:d} times a week."
        index = len(SPELL_FAILED_TYPE) + 13
        space = msg.rfind(" ", 0, -16)
        values.append(msg[18 : space])
        values.append(int(msg[space + 1 : -14]))
    
    elif startsWith(msg, "You can't change that talent choice while ") and endsWith(msg, " is on cooldown."):
        # "You can't change that talent choice while {0:s} is on cooldown."
        index = len(SPELL_FAILED_TYPE) + 14
        values.append(msg[42:-16])
    
    elif startsWith(msg, "You may only have one glyph of the ") and endsWith(msg, " type."):
        # "You may only have one glyph of the {0:s} type."
        index = len(SPELL_FAILED_TYPE) + 15
        values.append(msg[35:-6])
    
    elif startsWith(msg, "You need to be in ") and endsWith(msg, "."):
        # "You need to be in {0:s}."
        index = len(SPELL_FAILED_TYPE) + 16
        values.append(msg[18:-1])
    
    elif startsWith(msg, "Your skill is not high enough.  Requires ") and endsWith(msg, ")."):
        # "Your skill is not high enough.  Requires {0:s} ({1:d})."
        index = len(SPELL_FAILED_TYPE) + 17
        space = msg.rfind(" (")
        values.append(msg[41 : space])
        values.append(int(msg[space + 2 : -2]))

    else:
        assert(False)

    return index, values
