SPELL_FAILED_TYPE = [
    "Your skill is too high for this item.",
    "You are in combat",
    "That creature is already being tamed",
    "You already control a charmed creature",
    "You must dismiss your current pet first.",
    "You already control a summoned creature",
    "Already open",
    "Requires apprentice riding skill",
    "Your Artifact is too powerful to be modified by that item",
    "Spell Failed to create area trigger",
    "Your Artifact is at full power.",
    "Requires artisan riding skill",
    "A more powerful spell is already active",
    "No power choices to undo.",
    "Item is not Azerite empowered",
    "No target",
    "Invalid target",
    "Requires Battle for Azeroth Pathfinder skill.",
    "You already know that blueprint.",
    "The spell cannot be cast on beastmaster or invis god targets.",
    "Requires Broken Isles Pathfinder skill.",
    "The building is not ready to be activated.",
    "Can't Add Companion To Your Account",
    "Target can't be charmed",
    "Item cannot be disenchanted",
    "Your Enchanting skill is not high enough to disenchant that",
    "You cannot mill that",
    "Item cannot be obliterated",
    "There are no gems in this",
    "Target is tapped",
    "You can't do that right now.",
    "You can't start a duel while invisible",
    "You can't start a duel while stealthed",
    "Item's enchant visual cannot be modified.",
    "That item cannot be modified.",
    "You are too close to enemies",
    "You can't change that talent choice while {0:s} is on cooldown.",
    "Failed to Upgrade Pet",
    "You can't do that yet",
    "You are dead",
    "You are dead",
    "You can't cast that here",
    "Can't do that while charmed",
    "That is already being used",
    "Requires cold weather flying skill",
    "Can't do that while confused",
    "Requires Cloud Serpent Riding skill",
    "Something bad happened, and we want to display a custom message!",
    "You cannot summon another gargoyle yet.",
    "Three fawns are already following you!",
    "You already have a River Boat.",
    "You have no active enchantment to unleash.",
    "You have bound enough Highborne souls. Return to Arcanist Valdurian.",
    "You must be at least 40 yards away from all other Oil Drilling Rigs.",
    "You must be above the Enslaved Pearl Miner.",
    "You must target the corpse of a Seabrush Terrapin, Scourgut Remora, or Spinescale Hammerhead.",
    "Ambassador Slaghammer is already your prisoner.",
    "Requires a location that is attuned with the Naz'jar Battlemaiden.",
    "Requires Corpse Dust if the target is not dead and humanoid.",
    "Free the Drake from the net first!",
    "You already have three Dragonmaw allies following you.",
    "Requires Opposable Thumbs.",
    "Not enough health",
    "You already have enough Forsaken Troopers.",
    "You cannot jump to another boulder yet.",
    "Skill too high.",
    "You have already rescued 6 Survivors.",
    "You need to be facing the ships from the rescue balloon.",
    "You cannot supervise more than 5 Arrested Cultists at a time.",
    "Can only be placed near Shatterhorn",
    "You must reach level 85 to use this portal.",
    "Your target must be below 35% health.",
    "You must select a specialization first.",
    "You are too wise and powerful to gain any benefit from that item.",
    "You are within 10 yards of another Argent Lightwell.",
    "You can't do that while shapeshifted.",
    "You already have a Mana Gem in your bank.",
    "You must have at least one Flame Shock active.",
    "You cannot transform right now",
    "Your pet must be attacking a target.",
    "You must first select a Proto-Drake Egg.",
    "Requires Gnomish Engineering",
    "Requires Goblin Engineering",
    "You have no target.",
    "Your Pet is out of range of the target.",
    "You can't do that while holding the flag.",
    "You can't do that to targets holding the flag.",
    "The portal is not yet open.  Continue helping the druids at the Sanctuary of Malorne.",
    "You need to be closer to Aggra's Air Totem, in the west.",
    "You need to be closer to Aggra's Water Totem, in the north.",
    "You need to be closer to Aggra's Earth Totem, in the east.",
    "You need to be closer to Aggra's Fire Totem, near Thrall.",
    "You are facing the wrong way.",
    "You are within 10 yards of another Makeshift Dynamite.",
    "You must be near the sunken ship at Sapphire's End in the Jade Forest.",
    "That demon's health is already full.",
    "Wait until the Onyx Serpent is directly overhead.",
    "Your objective is already complete.",
    "You can only push Sad Panda towards Sad Panda Town!",
    "Target is already affected by Stardust No. 2.",
    "You cannot deconstruct Elementium Gem Clusters while collecting them!",
    "You must be close to a marked tree.",
    "You must target a Fjord Turkey.",
    "You don't have enough health.",
    "You cannot use the gateway yet.",
    "You must choose a specialization to use Ascendance.",
    "You have insufficient Blood Charges.",
    "No fully depleted runes.",
    "No more charges.",
    "Statue is out of range of the target.",
    "You don't have a statue summoned.",
    "You have no spirit active.",
    "Both Frost Fever and Blood Plague must be present on the target.",
    "You must target a Fjord Hawk.",
    "You can't do that while holding an Orb of Power.",
    "You can't do that while jumping or falling.",
    "You must be transformed by Polyformic Acid.",
    "There isn't enough acid left to store this transformation.",
    "You must obtain a Flight Master's License before using this spell.",
    "You have already sampled sap from this Feeder.",
    "Requires you to be near a Mantid Feeder in the Heart of Fear.",
    "Target must be directly in front of you.",
    "You can't do that while a Mythic Keystone is active.",
    "You are not the correct class for that mount.",
    "You are too far from the bouy.",
    "Nothing left to discover.",
    "There are no explosives available.",
    "You must be flagged for PvP.",
    "Requires Battle Rations or Meaty Haunch",
    "Requires Brittle Root",
    "Requires Laborer's Tool",
    "Requires Unexploded Cannonball",
    "Requires Misplaced Keg",
    "Requires Liquid Fire, Jungle Hops, or Spirit-kissed Water",
    "Requires Krasari Iron",
    "Must be used near an oil slick.",
    "Requires Spirit-Kissed Water",
    "Requires Snake Oil",
    "You can't do that while a Scenario is in progress.",
    "Requires the Darkmoon Faire to be open.",
    "Already at Valor cap",
    "Already commended by this faction",
    "Out of coins! Pickpocket humanoids to get more.",
    "Only one elemental spirit on a target at a time.",
    "You do not know how to tame Direhorns.",
    "You must be near the Bloodied Court gate.",
    "You must be closer to the buoy!",
    "You are not Electrified.",
    "There is nothing to be fetched.",
    "Requires The Thunder Forge.",
    "You cannot use the dice again yet.",
    "You are already a member of the Brawler's Guild.",
    "You may not change talent specializations during a celestial challenge.",
    "Your talent specialization does not match the selected challenge.",
    "You don't have enough currency to do that.",
    "Target cannot benefit from that spell",
    "You can only have one Healing Rain active at a time.",
    "Alex broke your quest! Thank him later!",
    "You may only call for the aid of a Wyrmrest Vanquisher in Wyrmrest Temple, The Dragon Wastes, Galakrond's Rest or The Wicked Coil.",
    "The door is locked.",
    "You need to select a customer who is waiting in line first.",
    "You may not change specialization while a trial is in progress.",
    "You must wait for customers to get in line before you can select them to be seated.",
    "Must be closer to one of Gazlowe's objectives to deploy!",
    "Must be closer to one of Thaelin's objectives to deploy!",
    "Your pack of volen is already full!",
    "Requires 600 Mining or Blacksmithing",
    "The Arkonite Protector is not in range.",
    "You are unable to have both Beacon of Light and Beacon of Faith on the same target.",
    "That can only be used on a Ice Heart Jormungar Spawn.",
    "Can only be used on AFK players.",
    "No lootable corpse in range",
    "Chimaeron is too calm to tame right now.",
    "You may only carry one type of Blackrock Munitions.",
    "You have run out of Blackrock Munitions.",
    "You are carrying the maximum amount of Blackrock Munitions.",
    "Target is too far away.",
    "Cannot use during a boss encounter.",
    "Must have a Melee Weapon equipped in both hands",
    "Your weapon has overheated.",
    "You must be closer to a sinkhole to use your map.",
    "You must be a party leader to queue your group.",
    "Not enough fuel",
    "You are already disguised!",
    "You need to be in a Shredder to chop this up!",
    "Food cannot eat food",
    "A mysterious force prevents you from opening the chest.",
    "You can't do that while holding Empowered Ore.",
    "Not enough Ammunition!",
    "You need Beatface the Sparring Arena gladiator to break this!",
    "You can only have one waygate open. Disable an activated waygate first.",
    "You may only call down a stampede on Harold Lane.",
    "You can only have two waygates open. Disable an activated waygate first.",
    "You can only have three waygates open. Disable an activated waygate first.",
    "Requires Mage Tower",
    "Requires Spirit Lodge",
    "A Frost Wyrm is already active.",
    "Not enough Runic Power",
    "You are the Party Leader.",
    "Yu'lon is already active.",
    "A Stampede is already active.",
    "You are already Well Fed.",
    "You may only use the Pouch of Crushed Bloodspore on Gammothra or other magnataur in the Bloodspore Plains and Gammoth.",
    "You cannot do that while under Suppressive Fire.",
    "You already have a piece of Murloc Slop.",
    "You don't have any Artifact Fragments.",
    "You aren't in a Party.",
    "Requires 30 Ammunition!",
    "Requires 20 Ammunition!",
    "You already have the maximum amount of Outcasts following you.",
    "Not in World PvP zone.",
    "Already at Resource cap",
    "This Apexis Sentinel requires energy from a nearby Apexis Pylon to be powered up.",
    "Requires the magmawyrm resurrection chamber in the back of the Maw of Neltharion.",
    "You must have 3 or fewer players.",
    "You have already read that treasure map.",
    "You may only use this item while your garrison is under attack.",
    "This spell requires active mushrooms for you to detonate.",
    "Requires a faster time with the basic racer",
    "Requires Inferno Shot Ammo!",
    "You cannot do that right now.",
    "A trap is already placed there.",
    "You are already on that quest.",
    "Requires a Felforged Cudgel!",
    "You may only call down a Wintergarde Gryphon in Wintergarde Keep or the Carrion Fields.",
    "Can't take while being damaged!",
    "You are bound to Draenor by Archimonde's magic.",
    "You already have the maximum number of ships your shipyard can support.",
    "You must be at your shipyard.",
    "Requires a level 3 Mage Tower.",
    "Requires a level 3 Spirit Lodge.",
    "You do not like Fel Eggs and Ham.",
    "You have already entered in to this trade agreement.",
    "You cannot steal that while guards are on duty.",
    "You have already used a Vantus Rune this week.",
    "What are you doing? Only aim that thing at Wilhelm!",
    "That item cannot be obliterated.",
    "No skinnable corpse in range",
    "You must be a Mercenary to use this trinket.",
    "You must be in combat.",
    "No enemies near target.",
    "Requires a Leyspine Missile",
    "Requires both currents connected.",
    "Can't do that while in demon form (yet)",
    "You do not know how to tame or obtain lore about Mechs.",
    "You cannot charm any more withered.",
    "Not enough health!",
    "Requires an active Healing Rain.",
    "You've already collected these appearances",
    "Cannot resurrect someone who has surrendered to madness",
    "You must be in Cat Form.",
    "You cannot Release Spirit yet.",
    "No fishing nodes nearby.",
    "You are not the correct specialization.",
    "Ulthalesh has no power without souls.",
    "You cannot cast that while talented into Voodoo Totem.",
    "You've already collected this appearance.",
    "There are no nearby corpses to use.",
    "Your total pet maximum is already this high.",
    "You do not have enough withered to do that.",
    "Requires a nearby Soul Fragment.",
    "Requires at least 10 living withered",
    "Requires at least 14 living withered",
    "Requires at least 18 living withered",
    "Requires 2 Withered Mana-Ragers",
    "Requires 1 Withered Berserker",
    "Requires 2 Withered Berserkers",
    "Target's health is too low",
    "This spell may only be used on Helpless Wintergarde Villagers that have not been rescued.",
    "You've created enough ghouls. Return to Gothik the Harvester at Death's Breach.",
    "You cannot shapeshift while riding Stormtalon",
    "You can not change specializations while in Combat Training.",
    "Unknown phenomenon is preventing a connection to the Leyline.",
    "The Nightmare obscures your vision.",
    "You are in the wrong class specialization.",
    "There are no valid corpses nearby.",
    "Can't cast that right now.",
    "Not enough Ancient Mana.",
    "Requires a Song Scroll to function.",
    "You must have an artifact weapon equipped.",
    "Your companion does not want to come here.  Go further from the Sundered Shard.",
    "Requires Cat Form.",
    "Requires Bear Form.",
    "Requires either a Conjured Mana Pudding or Conjured Mana Fritter.",
    "Requires an artifact weapon.",
    "You can't cast that here",
    "You cannot do that while on a Class Trial.",
    "You can only benefit from the Ritual of Doom once per day.",
    "You cannot perform the Ritual of Doom while attempting to summon the sisters.",
    "You have learned all that you can about your artifact.",
    "You cannot use Call Pet while Lone Wolf is active.",
    "Must be in Cat Form",
    "Target cannot already have a Orb of Power.",
    "You must be in an inn to strum that guitar.",
    "You cannot reach the latch.",
    "Requires a Brimming Keystone.",
    "You must be wielding the Underlight Angler.",
    "Your target must be Shackled.",
    "You already possess all of the knowledge contained in these pages.",
    "You can't risk getting the grummels wet!",
    "You cannot change specializations right now.",
    "You've reached the maximum number of Artifact Research Notes available.",
    "Only Death Knights may enter Ebon Hold.",
    "You don't have enough Nethershards.",
    "The Sentinax is not patrolling this area.",
    "The Sentinax cannot open another portal right now.",
    "You cannot gain additional reputation with this item.",
    "Can't do that while in Ghost Wolf form.",
    "Your supplies are frozen.",
    "You do not know how to tame Feathermanes.",
    "You must reach Artifact Knowledge level 25 to use the Tome.",
    "Requires a Nether Portal Disruptor.",
    "You are not the correct Rank to use this item.",
    "Must be in Bear Form",
    "Must be standing near the injured Chromie in Mount Hyjal.",
    "There's nothing further you can learn.",
    "You should remove the cannon's Heavy Iron Plating first.",
    "You should remove the cannon's Electrokinetic Defense Grid first.",
    "You are missing pieces of the Armory Key or do not have enough Dendrite Clusters.",
    "This item requires basic Obliterum to upgrade.",
    "This item requires Primal Obliterum to upgrade.",
    "This item requires a Flight Master's Whistle.",
    "Requires Morrison's Master Key.",
    "Will only open to one wielding the power that echoes that of the Augari.",
    "You must be within range of a Helpless Wintergarde Villager.",
    "That player has a pending Totemic Revival.",
    "You have no Fire Mines deployed.",
    "You must be affected by the Spirit Powder to take the phylactery.",
    "You are blocked by a structure above you.",
    "Requires 100 Imp Meat.",
    "You have not obtained any background filters.",
    "There is nothing interesting posted here right now.",
    "Paragon Reputation is not available until a higher level.",
    "Uuna is missing.",
    "Only other members of their Hivemind may join with them.",
    "You cannot target an elemental or mechanical corpse.",
    "No valid flask present.",
    "There are no Wild Imps to sacrifice.",
    "You are carrying too much Iron",
    "You have no Iron to collect",
    "You have no available Wild Imps.",
    "Needs repairs.",
    "You're carrying too much Wood.",
    "You're already carrying repair parts.",
    "You have not unlocked the Flight Whistle for this zone.",
    "There are no unlocked flight points nearby to take you to.",
    "This teleport crystal cannot be used until the teleport crystal in Dalaran has been used at least once.",
    "You must have a Felguard.",
    "The target has no Festering Wounds.",
    "You do not have Deadly Poison or Wound Poison active.",
    "You cannot read the soldier's dog tag without your headlamp on.",
    "You have no Wood to collect.",
    "You are not wearing a shirt!",
    "Target must be dead.",
    "Your target is already embiggified.",
    "You must target a Sinister Gladiator's item to upgrade.",
    "This item's level is too high for this upgrade.",
    "You are already holding something in your hand. You must throw the creature in your hand before picking up another.",
    "The ballista cannot be used while on fire.",
    "You must target a Dread Gladiator's item to upgrade.",
    "You do not know how to tame Blood Beasts.",
    "Can only be used in the evening.",
    "Requires Pa'ku to be your chosen loa.",
    "Requires V.I.G.O.R. Engaged.",
    "You can only have one treasure map mission at a time.",
    "You don't have anything to throw! Find a Vargul and use Gymer Grab to pick one up!",
    "You already have a Silas' Sphere of Transmuation.",
    "You do not have the Mallet of Thunderous Skins.",
    "You must have an open stable slot.",
    "Does not work on critters.",
    "Can only be used on Hati.",
    "You already have an Iwen's Enchanting Rod.",
    "You already have a Mallet of Thunderous Skins.",
    "Can only be used on Inert Tide Watchers or Inert Voodoo Masks.",
    "You must be at a Shrine to make an offering to a Loa.",
    "Requires that you be wearing the Warsong Orc Disguise.",
    "Bouldercrag's War Horn can only be used within 10 yards of Valduran the Stormborn.",
    "You are not carrying a passenger. There is nobody to drop off.",
    "You cannot build any more siege vehicles.",
    "You are already carrying a captured Argent Crusader. You must return to the Argent Vanguard infirmary and drop off your passenger before you may pick up another.",
    "You can't do that while rooted.",
    "Requires a nearby target.",
    "Nothing left to discover.",
    "No targets close enough to bluff.",
    "Your Iron Rune Construct is out of range.",
    "Requires Engineering (350)",
    "You must be closer to a plague wagon in order to drop off your 7th Legion Siege Engineer.",
    "You can't use that mount.",
    "There is nobody to eject!",
    "The target must be bound to you.",
    "Target must be undead.",
    "You have no target or your target is too far away.",
    "Missing Reagents: Dark Matter",
    "You can't use that item",
    "You can't do that while Cycloned",
    "Target is already affected by a similar effect",
    "That anti-venom is not strong enough to dispel that poison",
    "You cannot target friendly units outside your party.",
    "You must have a lance equipped.",
    "You must be near the Maiden of Winter's Breath Lake.",
    "You have learned everything from that book",
    "Your pet is dead.",
    "There are no valid targets within range.",
    "Only GMs may use that. Your account has been reported for investigation.",
    "You must reach level 58 to use this portal.",
    "You already have the maximum amount of honor.",
    "You already have a Hot Rod.",
    "This partygoer wants some more bubbly.",
    "You must target a weakened chill nymph.",
    "This partygoer needs a bucket!",
    "This partygoer wants to dance with you.",
    "This partygoer wants to see some fireworks.",
    "This partygoer wants some more hors d'oeuvres.",
    "The Goblin All-In-1-Der Belt's battery is depleted.",
    "You must have a demonic circle active.",
    "You already have maximum rage",
    "Requires Northrend Engineering (25)",
    "Your soul belongs to the Lich King",
    "Your attendant already has an Argent Pony",
    "The Imbued Scourge Shroud will only work when equipped in the Temple City of En'kilah.",
    "First, Overload the Defective Generator, Activate the Leaky Stove, and Drop a Cigar on the Flammable Bed.",
    "You've already sent in the Gasbot and destroyed headquarters!",
    "This goblin is all partied out!",
    "You must have a Magma, Flametongue, or Fire Elemental Totem active.",
    "You may not bite other vampires.",
    "Your pet is already at your level.",
    "You do not meet the level requirements for this item.",
    "There are too many Mutated Abominations.",
    "The potions have all been depleted by Professor Putricide.",
    "You have already defeated enough of them.",
    "Requires Corpse Dust",
    "Requires level 65",
    "You have already destroyed the KTC Oil Platform.",
    "You have already launched enough cages.",
    "Requires Single-Stage Booster Rockets. Return to Hobart Grapplehammer to get more.",
    "You have already captured enough wild cluckers.",
    "Requires Remote Control Fireworks. Return to Hobart Grapplehammer to get more.",
    "You already have the max number of recruits.",
    "You already have the max number of volunteers.",
    "Frostmourne has rendered you unable to resurrect.",
    "You can't mount while affected by that shapeshift.",
    "You can't do that while you are immune",
    "An aura is currently disabling this spell",
    "You are higher than the max usable level for this spell.",
    "Requires Draenor Pathfinder skill.",
    "Must have the proper item equipped",
    "Must have a {0:s} equipped",
    "Must have a {0:s} equipped in the main hand",
    "Must have a {0:s} equipped in the offhand",
    "Internal error",
    "You can only cast {0:s} {1:d} times a week.",
    "Requires expert riding skill",
    "Can't do that while falling",
    "Requires Fishing {0:d}",
    "Fizzled",
    "Can't do that while fleeing",
    "Requires flight master's license skill",
    "Floating mounts are not allowed here",
    "Flying mounts are not allowed here",
    "You cannot recruit any more of that troop type.",
    "You already have that follower.",
    "That food's level is not high enough for your pet",
    "That follower already has that ability.",
    "That follower already has a temporary ability.",
    "That follower is currently assigned to a building.",
    "That follower's power level exceeds the power of this spell.",
    "That follower is already max level.",
    "That follower's quality exceeds the power of this spell.",
    "That follower's power level is too low for the power of this spell.",
    "Follower must be max level.",
    "That follower has no available ability slots.",
    "That follower is currently on a mission.",
    "The targeted garrison follower must be at least of Epic quality to do that.",
    "That mission is already complete.",
    "That mission is not in progress.",
    "You don't own a garrison.",
    "You are not eligible for any new missions.",
    "You already own a garrison.",
    "You may only have one glyph of the {0:s} type.",
    "That glyph is invalid for your {0:s} specialization.",
    "That glyph requires a specialization.",
    "You cannot inscribe a glyph there yet.",
    "Ground mounts are not allowed here",
    "You already have that mission.",
    "Target is too high level",
    "Immune",
    "You are in the wrong zone.",
    "Interrupted",
    "Interrupted",
    "That glyph cannot be inscribed there.",
    "You can no longer resurrect during combat",
    "Item is already enchanted",
    "Item already has the maximum number of charges.",
    "Item cannot be enchanted in trade",
    "Item is gone",
    "Item is not a weapon.",
    "Tried to enchant an item that didn't exist",
    "Item is not ready yet",
    "Requires journeyman riding skill",
    "You are not high enough level",
    "Your pet is not high enough level",
    "You have too many of that item already",
    "Target not in line of sight",
    "Target is too low level",
    "Skill not high enough",
    "Your weapon hand is empty",
    "Requires master riding skill",
    "Your skill is not high enough.  Requires {0:s} ({1:d}).",
    "To use this mount in the current area you must be underwater.",
    "You have collected this mount but it is not usable on this character.",
    "To use this mount in the current area you must not be at the water's surface.",
    "To use this mount in the current area you must be above water.",
    "Can't do that while moving",
    "Must know previous spell rank to learn.",
    "All party members must be present to do that.",
    "Ammo needs to be in the paper doll ammo slot before it can be fired.",
    "Requires: {0:s}",
    "Requires exotic ammo: {0:s}",
    "Requires {0:d} {1:s}.",
    "No path available",
    "Nothing to dispel",
    "Nothing to steal",
    "You must be behind your target.",
    "You do not have enough currency to cast this spell.",
    "Not enough Work Orders pending for that building.",
    "Your cast didn't land in fishable water",
    "You are flying.",
    "You can't use that here.",
    "Can't use while Idle",
    "Can't use while Inactive",
    "You must be in front of your target.",
    "You can't do that in an arena.",
    "You can't do that in an arena.",
    "You can't do that while in the barber shop",
    "You can't do that in a battleground.",
    "You are not in control of your actions",
    "You can't do that in an LFG Dungeon.",
    "You can't do that in a raid instance.",
    "You can't do that in a rated battleground.",
    "Spell not learned",
    "You are mounted.",
    "Spell cannot be cast on a damage immune target.",
    "Cannot use on the ground",
    "Spell cannot be cast on a mounted unit.",
    "Cannot be cast on shapeshifted target.",
    "Spell cannot be cast on stealthed target.",
    "You are in flight",
    "You are on a transport",
    "Not yet recovered",
    "You are in shapeshift form",
    "Item must be soulbound.",
    "You must be standing to do that",
    "You can only use this on an object you own",
    "Tried to enchant a trade item, but not trading",
    "You must be unsheathed",
    "Can't cast while fatigued",
    "Can't cast as ghost",
    "You are busy looting",
    "You can't do that while you are a mercenary",
    "Can't cast while trading",
    "You can't take actions right now.",
    "You have no active glyphs to remove.",
    "Out of ammo",
    "You must have an artifact weapon equipped.",
    "Requires Bone Shield charges",
    "That building is not in your garrison.",
    "You haven't selected a champion",
    "No charges remain",
    "That ability requires combo points",
    "Dueling isn't allowed here.",
    "Requires engaging {0:s}",
    "There are no nearby corpses to eat",
    "Not enough endurance",
    "You need Evasive Charges",
    "There aren't any fish here",
    "Can't use items while shapeshifted",
    "Requires water surface",
    "No magic to consume",
    "You can't mount here.",
    "You do not have a pet.",
    "You can not do this. You have more than 5 hours of online time",
    "You have no pending Work Orders for that building.",
    "You need to choose a character specialization",
    "Leave Instance Group to exit.",
    "There is no available seat",
    "Cannot use while swimming",
    "Can only use in battlegrounds",
    "Can only use indoors",
    "You can only do that in an arena.",
    "Can only use while mounted",
    "Cannot use while swimming",
    "Can only use outside",
    "Must be in {0:s}",
    "You must be in stealth mode.",
    "Can only use while swimming",
    "Out of range",
    "Can't use that ability while pacified",
    "Requires Wisdom of the Four Winds skill",
    "You can not do this. You have more than 3 hours of online time. ",
    "You can already rename your pet",
    "You are possessed",
    "Can't do that while {0:s}",
    "Missing reagent: {0:s}",
    "Your reputation isn't high enough",
    "You need to be in {0:s}.",
    "Requires {0:s}",
    "You're too far away from Zafod's Transponster! The rocket pack won't fire.",
    "You are unable to move",
    "Item already has this enchant visual.",
    "Can't create any more Work Orders of that type.",
    "Can't do that while silenced",
    "You don't know that skill.",
    "That specialization has been disabled",
    "This spell is already known",
    "Another action is in progress",
    "You have already learned the spell",
    "The spell is not available to you",
    "That ability is not available to your pet",
    "Can't do that while stunned",
    "A summon is already pending",
    "Your target is dead",
    "Target is in combat",
    "You can't do that yet",
    "Target cannot be resurrected",
    "Target is currently dueling",
    "Target is hostile",
    "Target is too enraged to be charmed",
    "Target is currently in free-for-all PvP combat",
    "Target is friendly",
    "Target has a resurrection pending",
    "The target can't be in combat",
    "The target can't be in a pet battle",
    "Can't target players",
    "Can't target player controlled units",
    "Can't target trivial",
    "Target is locked to another raid instance",
    "Target is alive",
    "Target is not a ghost",
    "Target is not on the ground",
    "Target must be in this instance",
    "Target is not in your party",
    "Target is not in your party or raid group",
    "Target is not in a sanctuary",
    "Creature must be looted first",
    "Target is not a player",
    "No pockets to pick",
    "Target has no ranged weapons equipped",
    "Target has no weapons equipped",
    "Your target is in flight",
    "Creature is not skinnable",
    "Target too close",
    "You have too many of that item already",
    "Water too shallow",
    "Requires {0:s}",
    "Requires {0:s}",
    "Toy is already in your collection",
    "Toy Use Limit Reached",
    "You can't use the new item",
    "Failed attempt",
    "Underwater mounts are not allowed here",
    "That glyph is already inscribed in your spellbook.",
    "Target needs to be behind you.",
    "Target needs to be in front of you.",
    "Unknown reason",
    "Not available for Starter accounts",
    "Your vision of the target is obscured",
    "You have not provided enough items to cast this spell",
    "You have provided too many items to cast this spell",
    "That item is not a valid target.",
    "Wrong Pet Type",
    "Wrong Faction",
    "Your pet doesn't like that food.",
    "The weather isn't right for that",
    "You cannot use that in a PvP instance."
]