#pragma once

enum class EVENT_TYPE : unsigned char
{    
  DAMAGE_SHIELD = 0,
  DAMAGE_SHIELD_MISSED,
  DAMAGE_SPLIT,
  ENCHANT_APPLIED,
  ENCHANT_REMOVED,
  ENVIRONMENTAL_DAMAGE,
  PARTY_KILL,
  RANGE_DAMAGE,
  RANGE_MISSED,
  SPELL_ABSORBED,
  SPELL_AURA_APPLIED,
  SPELL_AURA_APPLIED_DOSE,
  SPELL_AURA_BROKEN,
  SPELL_AURA_BROKEN_SPELL,
  SPELL_AURA_REFRESH,
  SPELL_AURA_REMOVED,
  SPELL_AURA_REMOVED_DOSE,
  SPELL_CAST_FAILED,
  SPELL_CAST_START,
  SPELL_CAST_SUCCESS,
  SPELL_CREATE,
  SPELL_DAMAGE,
  SPELL_DURABILITY_DAMAGE,
  SPELL_DISPEL,
  SPELL_DRAIN,
  SPELL_ENERGIZE,
  SPELL_EXTRA_ATTACKS,
  SPELL_HEAL,
  SPELL_INSTAKILL,
  SPELL_INTERRUPT,
  SPELL_MISSED,
  SPELL_PERIODIC_DAMAGE,
  SPELL_PERIODIC_DRAIN,
  SPELL_PERIODIC_ENERGIZE,
  SPELL_PERIODIC_HEAL,
  SPELL_PERIODIC_LEECH,
  SPELL_PERIODIC_MISSED,
  SPELL_RESURRECT,
  SPELL_SUMMON,
  SWING_DAMAGE,
  SWING_DAMAGE_LANDED,
  SWING_MISSED,
  UNIT_DIED,
  UNIT_LOYALTY,
  COMBAT_LOG_VERSION,
  COMBATANT_INFO,
  UNKNOWN
};

const char* EVENT_NAMES[46] =
{
  "DAMAGE_SHIELD",
  "DAMAGE_SHIELD_MISSED",
  "DAMAGE_SPLIT",
  "ENCHANT_APPLIED",
  "ENCHANT_REMOVED",
  "ENVIRONMENTAL_DAMAGE",
  "PARTY_KILL",
  "RANGE_DAMAGE",
  "RANGE_MISSED",
  "SPELL_ABSORBED",
  "SPELL_AURA_APPLIED",
  "SPELL_AURA_APPLIED_DOSE",
  "SPELL_AURA_BROKEN",
  "SPELL_AURA_BROKEN_SPELL",
  "SPELL_AURA_REFRESH",
  "SPELL_AURA_REMOVED",
  "SPELL_AURA_REMOVED_DOSE",
  "SPELL_CAST_FAILED",
  "SPELL_CAST_START",
  "SPELL_CAST_SUCCESS",
  "SPELL_CREATE",
  "SPELL_DAMAGE",
  "SPELL_DURABILITY_DAMAGE",
  "SPELL_DISPEL",
  "SPELL_DRAIN",
  "SPELL_ENERGIZE",
  "SPELL_EXTRA_ATTACKS",
  "SPELL_HEAL",
  "SPELL_INSTAKILL",
  "SPELL_INTERRUPT",
  "SPELL_MISSED",
  "SPELL_PERIODIC_DAMAGE",
  "SPELL_PERIODIC_DRAIN",
  "SPELL_PERIODIC_ENERGIZE",
  "SPELL_PERIODIC_HEAL",
  "SPELL_PERIODIC_LEECH",
  "SPELL_PERIODIC_MISSED",
  "SPELL_RESURRECT",
  "SPELL_SUMMON",
  "SWING_DAMAGE",
  "SWING_DAMAGE_LANDED",
  "SWING_MISSED",
  "UNIT_DIED",
  "UNIT_LOYALTY",
  "COMBAT_LOG_VERSION",
  "COMBATANT_INFO"
};

const unsigned char EVENT_PARAM_COUNTS[44] =
{
  43, // DAMAGE_SHIELD
  20, // DAMAGE_SHIELD_MISSED
  43, // DAMAGE_SPLIT
  17, // ENCHANT_APPLIED
  17, // ENCHANT_REMOVED
  41, // ENVIRONMENTAL_DAMAGE
  14, // PARTY_KILL
  43, // RANGE_DAMAGE
  20, // RANGE_MISSED
  26, // SPELL_ABSORBED
  18, // SPELL_AURA_APPLIED
  19, // SPELL_AURA_APPLIED_DOSE
  18, // SPELL_AURA_BROKEN
  21, // SPELL_AURA_BROKEN_SPELL
  18, // SPELL_AURA_REFRESH
  18, // SPELL_AURA_REMOVED
  19, // SPELL_AURA_REMOVED_DOSE
  18, // SPELL_CAST_FAILED
  17, // SPELL_CAST_START
  33, // SPELL_CAST_SUCCESS
  17, // SPELL_CREATE
  43, // SPELL_DAMAGE
  19, // SPELL_DURABILITY_DAMAGE
  21, // SPELL_DISPEL
  37, // SPELL_DRAIN
  37, // SPELL_ENERGIZE
  18, // SPELL_EXTRA_ATTACKS
  38, // SPELL_HEAL
  17, // SPELL_INSTAKILL
  20, // SPELL_INTERRUPT
  20, // SPELL_MISSED
  43, // SPELL_PERIODIC_DAMAGE
  37, // SPELL_PERIODIC_DRAIN
  37, // SPELL_PERIODIC_ENERGIZE
  38, // SPELL_PERIODIC_HEAL
  37, // SPELL_PERIODIC_LEECH
  19, // SPELL_PERIODIC_MISSED
  17, // SPELL_RESURRECT
  17, // SPELL_SUMMON
  40, // SWING_DAMAGE
  40, // SWING_DAMAGE_LANDED
  16, // SWING_MISSED
  14, // UNIT_DIED
  15  // UNIT_LOYALTY
};

const unsigned char EVENT_PREFIX_PARAM_COUNTS[44] =
{
  3, // DAMAGE_SHIELD
  3, // DAMAGE_SHIELD_MISSED
  3, // DAMAGE_SPLIT
  3, // ENCHANT_APPLIED
  3, // ENCHANT_REMOVED
  0, // ENVIRONMENTAL_DAMAGE
  0, // PARTY_KILL
  3, // RANGE_DAMAGE
  3, // RANGE_MISSED
  3, // SPELL_ABSORBED
  3, // SPELL_AURA_APPLIED
  3, // SPELL_AURA_APPLIED_DOSE
  3, // SPELL_AURA_BROKEN
  3, // SPELL_AURA_BROKEN_SPELL
  3, // SPELL_AURA_REFRESH
  3, // SPELL_AURA_REMOVED
  3, // SPELL_AURA_REMOVED_DOSE
  3, // SPELL_CAST_FAILED
  3, // SPELL_CAST_START
  3, // SPELL_CAST_SUCCESS
  3, // SPELL_CREATE
  3, // SPELL_DAMAGE
  3, // SPELL_DURABILITY_DAMAGE
  3, // SPELL_DISPEL
  3, // SPELL_DRAIN
  3, // SPELL_ENERGIZE
  3, // SPELL_EXTRA_ATTACKS
  3, // SPELL_HEAL
  3, // SPELL_INSTAKILL
  3, // SPELL_INTERRUPT
  3, // SPELL_MISSED
  3, // SPELL_PERIODIC_DAMAGE
  3, // SPELL_PERIODIC_DRAIN
  3, // SPELL_PERIODIC_ENERGIZE
  3, // SPELL_PERIODIC_HEAL
  3, // SPELL_PERIODIC_LEECH
  3, // SPELL_PERIODIC_MISSED
  3, // SPELL_RESURRECT
  3, // SPELL_SUMMON
  0, // SWING_DAMAGE
  0, // SWING_DAMAGE_LANDED
  0, // SWING_MISSED
  0, // UNIT_DIED
  0  // UNIT_LOYALTY
};
